### ISSUE TITLE
Error: Broken DAG: [/home/airflow/gcs/dags/airflow_utils.py] 'DEPLOYMENT_SETUP'

### ISSUE THREAD

**Issue by ggupta36** [sungchun12/airflow-toolkit#12]
Hi,

Thanks for your help last time. I am trying to run Toolkit # 3 now but facing the below error:

```Broken DAG: [/home/airflow/gcs/dags/airflow_utils.py] 'DEPLOYMENT_SETUP'```
<img width="1316" alt="Screenshot 2020-12-17 at 9 07 33 PM" src="https://user-images.githubusercontent.com/62702390/102511266-97312680-40ae-11eb-8d05-1fbacfe1b014.png">

Also I have a question in regards to composer private IP:

a. I wish to pull from github instead of using google source repo for which there are 2 options. Either setup a Cloud NAT gateway OR disable private IP. Will it not defeat the purpose of having secure composer env in latter case ?

**Comment by sungchun12** [comment]
@ggupta36 I don't have time to make changes this week as I'm on vacation, but below is my initial reasoning for why Toolkit 3 is not working.

Problem: The `DEPLOYMENT_SETUP` environment variable is not created at composer startup time
[Source File](https://github.com/sungchun12/airflow-toolkit/blob/master/terraform_simple_setup/cloud_composer/variables.tf#L120)

Proposed Solution: Add in the `DEPLOYMENT_SETUP` environment variable similar to how the terragrunt modules are configured. This change will be made in the above terraform simple setup file: `terraform_simple_setup/cloud_composer/variables.tf`
[Source File](https://github.com/sungchun12/airflow-toolkit/blob/master/terragrunt_infrastructure_modules/cloud_composer/variables.tf#L122)

For your private IP question, having a public IP Composer instance will lower security and the tradeoff that comes with it is easier access to external resources. So for some users, it will lower security standards enough to not ever use that public configuration. For Cloud NAT gateway, that is out of scope for this toolkit.

**Comment by ggupta36** [comment]
Thank you for the solution. I tested and it's working fine

**Comment by sungchun12** [comment]
@ggupta36 Thanks for verifying it worked. I'll close this issue, and feel free to open more as questions come up!
